### login
POST {{url}}/auth/login
Content-Type: application/json

{
  "username": "temp",
  "password": "temp",
  "clientId": "my",
  "clientSecret": "my",
  "codeChallenge": "plP8aHmykBUgarC_HDHzGmYhnJiipBy69FE8KWoLMqI",
  "redirect": "http://localhost:3000/"
}

### authorize
POST {{url}}/auth/authorize
Content-Type: application/json

{
  "clientId": "my",
  "clientSecret": "my",
  "authorizationCode": "FZukFe2xCsz3abtmYUPTmNCQ0WKVDAhsjXqIgeIEIe2frR9ph0N37PmegirBLsdHN4cplKtdzRJ1L84qZaAiwY7i45TwK4ObHt0rX2JJ9uy73Su33Z8BfVQFB4wxZczf",
  "codeVerifier": "tpWFpflpskMgYA"
}

### refresh
POST {{url}}/auth/refresh
Content-Type: application/json

{
  "clientId": "my",
  "clientSecret": "my",
  "refreshToken": "0hUzVRZO8JJqiXCkKOvQFMOE3ovatTV2mlHrU3XaFle4j1aHugU7MoUUqzD4KnF5n1JZXaWXrNAVil5fJMW1RWq55M7AO5lwBb5pVQAVV6INxr8Zm8jF0uy6stgTpbUr"
}

### verify
POST {{url}}/auth/verify
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImRlbW8iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOlsibXkiXSwiY2xpZW50SWQiOiJteSIsImV4cCI6MTY5MjA4Njk5NiwiaWF0IjoxNjkyMDgzMzk2LCJpc3MiOiJkZW1vIiwibmJmIjoxNjkyMDgzMzk2LCJ1c2VybmFtZSI6InRlbXAiLCJ1dWlkIjoiYTMzZTNjYzAtNzNlNS00ZjRkLWJmMzQtNTNjMWE0MWM2ZjNmIn0.GUR3HrYMDm_9FVCm34H6mSLdYeDGHkLp-SWC7W0QPmctoFJVKfUBENocE6aT8XNak8rfdeidd2ErLlO6Adhb4uQ6mB0N025LjYyxSHiJ7zeT38kfwDlg2_suHJQlO7ezA_FM_VfqM3B-KsdT2CyPlvfIW7_iIAFZEs4NNZY5cX1DbQyWAL-0HYc_UmYtoRQj7DN0jkdy--vRgIrEq3faGaK-TLBH7Dy764Rg7h1l_ZgfVsVpH8vKark9NwxIbgWU2URcAodA-mIcoEQhtrrwBtnoheKsDjKcCDLTJ7uZsifE5TrfjO9uKmTFrPD7vR58vNkxvVkgWD8SDd2a4LsJlA"
}